# 如果希望配置能在中注册对象中生效，清将其放在一级目录下。然后在函数中解析。
# 可参考 llm/chat_openai.py 中ServeChatModel的init函数。

serve_chat_model_config:
  openai_api_base: "http://192.168.100.111:8001/v1"
  model: "qwen2-pro"
  max_tokens: 30000
  openai_api_key: "dummy"

remember_history: 8

profile_query_prompt:
  path: ../resources/profile-query-prompt.yml

profiled_query_prompt:
  path: ../resources/profiled-query-prompt.yml

qdrant_config:
  location: "http://192.168.100.111:6333"
qdrant_vectorstore_config:
  collection_name: "word_pic_reader_test_1024"
retriever_config:
  k: 5
  score_threshold: 0.65
xinference_embedding_config:
  server_url: "http://192.168.100.111:9997"
  model_uid: "bge-m3"

profiles:
  includes:
#    可以引入多个yaml配置文件，但是需要避免循环依赖，顺序会影响，最后的优先级最高
#    - application-2.yaml
